[#302] Modify Font Size & Color of Moment-View page
justin-cotarla/CaptionThis pull request #303
Opened 2018-03-22 04:48 UTC by yasminegha

2018-03-22 17:52 UTC, tehblasian requested changes
The caption highlight animation as well as the accept/reject feedback is broken. Also, the caption font color should only be changed for the MomentViewPage, as it is unreadable on the profile page.

2018-03-22 17:52 UTC, tehblasian commented on frontend/src/styles/Caption.css
> -.caption-highlighted {
the class .caption-highlighted should not be deleted, and all of the @keyframes stuff as well.

2018-03-22 17:52 UTC, tehblasian commented on frontend/src/styles/Caption.css
> -.caption-container-accepted {
restore this class

2018-03-22 17:52 UTC, tehblasian commented on frontend/src/styles/Caption.css
> -.caption-container-rejected {
restore this class

2018-03-22 20:01 UTC, ZacharyBys commented on frontend/src/styles/Caption.css
> +.caption-container h1 {
Everywhere caption-container is defined, caption-container-accepted and caption-container-rejected should also have the same style

2018-03-22 20:01 UTC, ZacharyBys commented on frontend/src/styles/Caption.css
> +.caption-container .caption-content h1 a{
Everywhere caption-container is defined, caption-container-accepted and caption-container-rejected should also have the same style

2018-03-22 20:02 UTC, ZacharyBys requested changes
See Comment

2018-03-22 20:04 UTC, DYu24 commented on frontend/src/styles/Caption.css
> +
Remove whitespace and extra semicolon

2018-03-23 03:11 UTC, ZacharyBys requested changes
The accept/reject feedback is broken with this change.

2018-03-23 03:11 UTC, ZacharyBys commented on frontend/src/components/Header.js
> +                headerStyle.fontSize = '24px';
Theres already a case where fontSize is 24px

2018-03-23 03:11 UTC, ZacharyBys commented on frontend/src/styles/Caption.css
> -.caption-container {
Why is this deleted? this was part of the accept/reject feedback

2018-03-23 03:11 UTC, ZacharyBys commented on frontend/src/styles/MomentView.css
> +.caption-container h1 {
again, should be defined for caption-container-accepted and caption-container-rejected

2018-03-23 03:11 UTC, ZacharyBys commented on frontend/src/styles/MomentView.css
> +.caption-container {
Here as well

2018-03-23 18:24 UTC, ZacharyBys submitted a review, later dismissed
Hm.

2018-03-25 01:36 UTC, tehblasian approved these changes

2018-03-25 01:37 UTC, tehblasian commented
Looks good. I just fixed some small issues that came up after merging with dev.

2018-03-25 02:03 UTC, merged