Adds filtering to caption list
justin-cotarla/CaptionThis pull request #306
Opened 2018-03-23 02:38 UTC by tehblasian

2018-03-23 02:50 UTC, tehblasian commented
There is a bug in the branch, do not review

2018-03-23 03:04 UTC, tehblasian commented
Bug is fixed

2018-03-23 15:44 UTC, justin-cotarla requested changes

2018-03-23 15:44 UTC, justin-cotarla commented on frontend/src/util/apiUtil.js
> +export const getToken = () => {
This is already in AuthUtil.js

2018-03-23 15:44 UTC, justin-cotarla commented on frontend/src/pages/ProfilePage.js
> +        const token = getToken();
Token is available in the props

2018-03-23 15:44 UTC, justin-cotarla commented on frontend/src/pages/ProfilePage.js
> +                                <CaptionList
Pass one function only

2018-03-23 15:44 UTC, justin-cotarla commented on frontend/src/pages/ProfilePage.js
> +                                        showCount={false}
Implement this later to show the total caption count

2018-03-23 15:44 UTC, justin-cotarla commented on frontend/src/util/apiUtil.js
> +export const fetchCaptionsByMomentId = (momentid, token) => {
Export a single `fetchCaptions` function that takes several params and internally handles building the query.

2018-03-23 15:44 UTC, justin-cotarla commented on frontend/src/util/apiUtil.js
> +export const fetchUserMoments = (id, token) => {
Export a single `fetchMoments` function that takes several params and internally handles building the query.

2018-03-23 15:44 UTC, justin-cotarla commented on frontend/src/pages/MomentViewPage.js
> +import { fetchCaptionsByMomentId, getFilteredCaptionsByMoment } from '../util/apiUtil';
Import one function only

2018-03-23 15:44 UTC, justin-cotarla commented on frontend/src/pages/MomentViewPage.js
> +    onCaptionSubmit = (momentId) => {
Don't leak CaptionList functionality here, rather just force it to re-render.

2018-03-23 15:44 UTC, justin-cotarla commented on frontend/src/components/CaptionList.js
> +                scrolled: true,
All scrolling should be handled here, not in caption

2018-03-23 15:44 UTC, justin-cotarla commented on frontend/src/components/CaptionList.js
> +            console.log(error);
Don't leave these here

2018-03-23 15:44 UTC, justin-cotarla commented on frontend/src/components/CaptionList.js
> +                                    wrap={children => <Link className="linked-caption" to={{pathname: `/moment/${caption.moment_id}`, state: { scrollTo: caption.caption_id}}}>{children}</Link>}
Break this up

2018-03-23 15:44 UTC, justin-cotarla commented on frontend/src/components/CaptionFilter.js
> +    const filters = ['Recent', 'Oldest', 'Top', 'Worst', 'Accepted', 'Rejected'];
Have these defined as constants elsewhere

2018-03-24 02:31 UTC, justin-cotarla requested changes

2018-03-24 02:31 UTC, justin-cotarla commented on frontend/src/util/apiUtil.js
> +export const fetchCaptions = ({ token, type, filter, momentId, userId }) => {
I would move this out into something like `getRequestTypeQuery` or something, and give it a similar implementation to `getFilterQuery`. That way this part would remain modular.

2018-03-24 19:46 UTC, justin-cotarla approved these changes
:eyes: good, will make fetching captions great again.

2018-03-24 23:42 UTC, merged