[#86] Create POST endpoints for caption voting
justin-cotarla/CaptionThis pull request #88
Opened 2018-02-14 05:20 UTC by DYu24

2018-02-14 15:01 UTC, tehblasian requested changes
The endpoint shouldn't return anything except the status code. The value of the counter will be managed on the frontend.

2018-02-14 16:43 UTC, tehblasian requested changes

2018-02-14 16:43 UTC, tehblasian commented on backend/app/routes/captions.js
> +        // Check if the caption id is valid
You also need to check if the captionId is only digits (regex)

2018-02-14 17:08 UTC, tehblasian requested changes
Just noticed, you need to check if the caption exists and handle the error if it doesn't exist. Either you check the error code from the db and give a different response depending on the db error, or you do a separate check beforehand to see if the caption exists. The return code should be 404

2018-02-14 20:31 UTC, tehblasian requested changes

2018-02-14 20:31 UTC, tehblasian commented on backend/app/routes/captions.js
> +        return databaseUtil.sendQuery(checkQuery, [captionId]).then((result) => {
You should refactor the code so that the promises are chained. See https://github.com/justin-cotarla/CaptionThis/pull/96/files

2018-02-15 15:39 UTC, justin-cotarla requested changes
Change voting to from relative to absolute voting. Use restful implementation.

2018-02-15 21:33 UTC, justin-cotarla submitted a review, later dismissed

2018-02-15 21:41 UTC, justin-cotarla requested changes
Make the .then()'s go on new lines to make it more legible

2018-02-15 22:05 UTC, tehblasian submitted a review, later dismissed
Great! This will make voting on captions great again.

2018-02-15 22:33 UTC, justin-cotarla submitted a review, later dismissed
Looks good, will make voting great again.

2018-02-16 00:09 UTC, tehblasian approved these changes
Perfect, this will make keeping track of the votes on the frontend great again.

2018-02-16 00:12 UTC, merged